name: ndosanga
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  carousel_slider: ^1.3.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - imagens/
    